- name: Install epel repository (CentOS)
  yum:
    name: epel-release
  when: ansible_distribution == "CentOS"

- name: Update all packages (CentOS)
  yum:
    name: '*'
    state: latest
  when: ansible_distribution == "CentOS"

- name: Install base packages (CentOS)
  yum:
    name: "{{ item }}"
  with_items:
    - chrony
    - firewalld
    - vim
  when: ansible_distribution == "CentOS"

- name: Install base packages (FreeBSD)
  pkgng:
    name: "{{ item }}"
    state: present
  with_items:
    - vim
  when:
    ansible_distribution == "FreeBSD"

- name: Install SELinux Library
  yum:
    name: libselinux-python
  when: ansible_distribution == "CentOS"

- name: Copy chrony.conf (CentOS)
  copy:
    src: templates/chrony.conf
    dest: /etc/chrony.conf
    mode: 0644
    owner: root
    group: root
  when: ansible_distribution == "CentOS"

- name: Start and Enable services (CentOS)
  systemd:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items:
    - chronyd.service
    - firewalld.service
  when: ansible_distribution == "CentOS"

- name: Disable SELinux - setenforce (CentOS)
  shell: setenforce 0
  when: ansible_distribution == "CentOS"

- name: Disable SELinux - Copy config file (CentOS)
  copy:
    src: templates/selinux.config
    dest: /etc/selinux/config
    mode: 0644
    owner: root
    group: root
  when: ansible_distribution == "CentOS"
