- name: Install Apache (CentOS)
  yum:
    name: httpd
  when: ansible_distribution == "CentOS"

- name: Copy Apache config files (CentOS)
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0644
    owner: root
    group: root
  with_items:
    - { src: "templates/centos-httpd.conf",    dest: "/etc/httpd/conf/httpd.conf" }
    - { src: "templates/centos-userdir.conf",  dest: "/etc/httpd/conf.d/userdir.conf" }
    - { src: "templates/centos-00-base.conf" , dest: "/etc/httpd/conf.modules.d/00-base.conf"}
  when: ansible_distribution == "CentOS"

- name: Start and Enable Apache (CentOS)
  systemd:
    name: httpd.service
    enabled: yes
    state: started
  when: ansible_distribution == "CentOS"

- name: Allow HTTP (CentOS)
  firewalld:
    service: http
    state: enabled
    permanent: true
    immediate: true
  when: ansible_distribution == "CentOS"

